name: Update IPTV List (Debug)

on:
  schedule:
    - cron: "0 0 * * *"   # 每天 0 点运行
  workflow_dispatch:       # 手动触发

permissions:
  contents: write   # ✅ 允许写入仓库内容

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show environment info
        run: |
          echo "=== GITHUB REF INFO ==="
          echo "Branch: $GITHUB_REF"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Actor: $GITHUB_ACTOR"
          echo "Workspace: $GITHUB_WORKSPACE"
          python3 --version
          git --version

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run IPTV fetcher
        run: |
          echo "=== Running IPTV Fetcher ==="
          python fetch_china_iptv.py --probe || { echo "❌ Script failed"; exit 1; }
          echo "✅ Script completed"

      - name: Check generated file
        run: |
          echo "=== Checking output file ==="
          ls -lh
          head -n 20 china_tv_alive.m3u || echo "⚠️ No output file"

      - name: Move alive list to tv.m3u
        run: |
          mv china_tv_alive.m3u tv.m3u || echo "⚠️ Move failed, file may not exist"
          ls -lh tv.m3u || echo "⚠️ tv.m3u not found"

      - name: Git status before commit
        run: |
          echo "=== Git Status Before Commit ==="
          git status
          git diff --stat || true

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tv.m3u
          git commit -m "Auto update tv.m3u ($(date -u '+%Y-%m-%d %H:%M:%S'))" || echo "⚠️ No changes to commit"
          echo "=== Try pushing changes ==="
          git push || { echo "❌ Git push failed"; exit 1; }
